### ISSUE TITLE
Documentation website crash after some click

### ISSUE THREAD

**Issue by MangelMaxime** [Dzoukr/Feliz.Quill#1]
Error message: `Error: Destroying editor before instantiation`

Reproduction step:

1. Go to https://dzoukr.github.io/Feliz.Quill/#/
2. Click on Installation
3. Click on Quickstart
4. Click on Toolbars
5. Click on Themes
6. Click on Toolbars
7. Click on Quickstart

This order seems to make it crash all the time. 

You can also click around 7-10 times on different menu and it seems to reproduce the error too.

**Comment by Dzoukr** [comment]
Yup, working on it. It has something to do with component lifecycle and fact that number of components differs between pages. But not sure really.

**Comment by Dzoukr** [comment]
Ok guys - @MangelMaxime, @zaid-ajaj - calling for help. What I missed in implementation that these components shares the value instead of having unique when paging?

![editor](https://user-images.githubusercontent.com/851307/103813608-a9c0cf00-5060-11eb-8368-15aea5119d1f.gif)

**Comment by MangelMaxime** [comment]
Hum it remind me of a problem I had on one of my application.

If the DOM between 2 pages is "similar" it is possible that React decide to not destroy the DOM but reuse all or part of the DOM/Components. You can try to force/help React tree diffing by using a `prop.key` with a unique name per page.

I don't know if you will need it at the "root" of the pages or if adding it at the "Quill" component will be enough in your case.

**Comment by Dzoukr** [comment]
Ufff, thanks for all the help! Fixed now.
